// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehUGBhLAFPQ2jMG58PVEOOxCl6eQItow',
    appId: '1:878611930487:web:44be3c293589ab7a211572',
    messagingSenderId: '878611930487',
    projectId: 'research-hub-d7341',
    authDomain: 'research-hub-d7341.firebaseapp.com',
    storageBucket: 'research-hub-d7341.firebasestorage.app',
    measurementId: 'G-HQD7BKLMPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa7neh3czA3RSvse62QRl77Hh87GoTtjo',
    appId: '1:878611930487:android:f5fa406f64a0f258211572',
    messagingSenderId: '878611930487',
    projectId: 'research-hub-d7341',
    storageBucket: 'research-hub-d7341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh6ZHqPu6hO4-Zswi8qYJizsrQ5gbYG3s',
    appId: '1:878611930487:ios:ca4afa04b1a991b5211572',
    messagingSenderId: '878611930487',
    projectId: 'research-hub-d7341',
    storageBucket: 'research-hub-d7341.firebasestorage.app',
    iosBundleId: 'com.example.researchHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh6ZHqPu6hO4-Zswi8qYJizsrQ5gbYG3s',
    appId: '1:878611930487:ios:ca4afa04b1a991b5211572',
    messagingSenderId: '878611930487',
    projectId: 'research-hub-d7341',
    storageBucket: 'research-hub-d7341.firebasestorage.app',
    iosBundleId: 'com.example.researchHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDehUGBhLAFPQ2jMG58PVEOOxCl6eQItow',
    appId: '1:878611930487:web:5cf9789d25665eec211572',
    messagingSenderId: '878611930487',
    projectId: 'research-hub-d7341',
    authDomain: 'research-hub-d7341.firebaseapp.com',
    storageBucket: 'research-hub-d7341.firebasestorage.app',
    measurementId: 'G-X63S40L710',
  );
}